// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"github.com/ljsea6/restful-api/app/controller"
	"github.com/ljsea6/restful-api/app/repository"
	"github.com/ljsea6/restful-api/app/service"
)

// Injectors from wire.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	userRepositoryImpl := repository.UserRepositoryImplInit(gormDB)
	userServiceImpl := service.UserServiceImplInit(userRepositoryImpl)
	userControllerImpl := controller.UserControllerImplInit(userServiceImpl)
	initialization := NewInitialization(userRepositoryImpl, userServiceImpl, userControllerImpl)
	return initialization
}

// wire.go:

var db = wire.NewSet(ConnectToDB)

var userRepoSet = wire.NewSet(repository.UserRepositoryImplInit, wire.Bind(new(repository.IUserRepository), new(*repository.UserRepositoryImpl)))

var userServiceSet = wire.NewSet(service.UserServiceImplInit, wire.Bind(new(service.IUserService), new(*service.UserServiceImpl)))

var userCtrlSet = wire.NewSet(controller.UserControllerImplInit, wire.Bind(new(controller.IUserController), new(*controller.UserControllerImpl)))
